### ISSUE TITLE
Bot No Longer Detects that the Game is Running.

### ISSUE THREAD

**Issue by MWEckert** [ilpersi/BHBot#138] opened 2019-12-03 04:04 UTC
When I try to load the bot, I get the initial text,

21:01:44,898 INFO - BHBot v43 build on Mon Dec 02 20:59:31 MST 2019 started.
21:01:44,902 INFO - GIT commit id: b6d9a70f1f5d3ebf58a9f1ffec857bc1f095879e  time: 2019-11-23T22:45:30+0100
21:01:45,484 INFO - Settings loaded from file
21:01:45,485 INFO - Character: 
21:01:46,602 INFO - Bot started successfully!
Starting ChromeDriver 2.44.609538 (b655c5a60b0b544917107a59d4153d4bf78e1b90) on port 19019
Only local connections are allowed.

And then nothing.  I've tried everything but a complete reinstall of chromedriver/chromium.  IT was happening sporadically in a previous version, but I would just type 'reset' and it would normally pick it back up.  Now I get nothing.

**Comment by MWEckert** [comment] 2019-12-03 04:08
Eventually, it times out and displays,

[1575346009.000][SEVERE]: Timed out receiving message from renderer: 299.226
[1575346009.001][SEVERE]: Timed out receiving message from renderer: -0.002
21:06:49,013 ERROR - Something went wrong with driver restart. Will retry in a few minutes... (sleeping)
 org.openqa.selenium.TimeoutException: timeout
  (Session info: chrome=69.0.3497.0)
  (Driver info: chromedriver=2.44.609538 (b655c5a60b0b544917107a59d4153d4bf78e1b90),platform=Windows NT 10.0.17763 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: _[deleted]_
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.44.609538 (b655c5a60b0b54..., userDataDir: ./chrome_profile}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:51317}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: ignore, unhandledPromptBehavior: ignore, version: 69.0.3497.0, webStorageEnabled: true}
Session ID: 5c7b2556850f651154e48911bf46bf7d
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_201]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_201]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_201]
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214) ~[BHBot.jar:?]
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166) ~[BHBot.jar:?]
        at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40) ~[BHBot.jar:?]
        at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80) ~[BHBot.jar:?]
        at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44) ~[BHBot.jar:?]
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158) ~[BHBot.jar:?]
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83) ~[BHBot.jar:?]
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552) ~[BHBot.jar:?]
        at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:277) ~[BHBot.jar:?]
        at org.openqa.selenium.remote.RemoteWebDriver$RemoteNavigation.to(RemoteWebDriver.java:857) ~[BHBot.jar:?]
        at MainThread.restart(MainThread.java:830) [BHBot.jar:?]
        at MainThread.run(MainThread.java:922) [BHBot.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by MWEckert** [comment] 2019-12-03 04:36
Oh, and sometimes it will find the game element, but doesn't actually do anything.  Attempts to 'do raid' forces the raid with zero change.  Then it just times out again.

**Comment by ilpersi** [comment] 2019-12-03 07:06
When this is happening, how many Chromium instances is the bot running? Can you check that it is only one?

**Comment by Fortigate** [comment] 2019-12-03 08:00
By any chance does the window title have a 'Select' prefix?

![image](https://user-images.githubusercontent.com/46250387/70031337-4a65d500-15ab-11ea-8a5c-35764f383202.png)

**Comment by MWEckert** [comment] 2019-12-03 11:16
ilpersi:  Only one instance of Chromium is running on the desktop.
Fortigate: It does not.

**Comment by MWEckert** [comment] 2019-12-03 11:35
I had a similar issue earlier and had the idea to delete the 'chrome_profile' folder.  Reran init.bat, and now it seems to be working without issue.

**Comment by Fortigate** [comment] 2019-12-03 13:36
Good to hear, I'll add that fix to the frequent issues list

**Comment by ilpersi** [comment] 2019-12-03 22:47
I am having similar issues and this is happening when Chrome crashes.

In those circumstances, the bot throws a timeout error and the Chromium windows become unresponsive, so when the bot tries to reboot two windows are present.

**Comment by MWEckert** [comment] 2019-12-12 11:12
Recently I'm having a resurgence of this issue.  The bot will crash, and appears to dissociate ffrom chromium.  So, I only have one (1) window, but it never recovers from what seems like frequent crashes.

**Comment by Fortigate** [comment] 2019-12-12 13:06
I've had similar issue recently as I've been having internet issues, after a crash (due to no connection) and restart the bot doesn't reassociate with the open chrome session, and hangs.

**Comment by MWEckert** [comment] 2019-12-13 03:22
I think I've figured out what triggers the frequent crashes I was having.  Any time the bot couldn't read a value, due to hover text from alerts/notifications/etc, it would be unable to recover and time-out.  Then, when it attempted to restart, it couldn't re-associate with the new window.

**Comment by ilpersi** [comment] 2019-12-13 09:16
Timeout is exactly the issue and I've put some code to manage it but it seems it is not effective.

The issue is that when I timeout is triggered, it seems that the bound between the bot and Chrome is broken and there is no way to restore it.

One question: when you get this kind of error, the bot should create a screenshot with the error. What do you see in that screenshot? Is it just the bot window or the whole desktop?

Thank you.

**Comment by MWEckert** [comment] 2019-12-13 16:26
Just the bot eindow.

**Comment by ilpersi** [comment] 2020-01-02 14:36
@MWEckert  The new [v44pr1](https://github.com/ilpersi/BHBot/releases/tag/v44pr1) has some improvements on this issue even if they can not be considered a final solution: can you have a test with it?

**Comment by MWEckert** [comment] 2020-01-02 15:15
Alright. I'll look into it when I get an opportunity.

**Comment by ilpersi** [comment] 2020-01-31 08:36
@MWEckert how is it going? This is not happening anymore for me lately

**Comment by MWEckert** [comment] 2020-01-31 18:51
It's not as frequent, but it still happens. It seems there's a fairly large
chance when it resets to dissociate with chromium.

**Comment by ilpersi** [comment] 2020-01-31 19:09
Can you please add the `useDoNotShareURL 1` parameter to your `settings.ini` and try again?

It is not a fix, but it will run BH without the Kongregate interface consuming fewer resources. For me it seems to reduce the issues.

**Comment by MWEckert** [comment] 2020-01-31 19:13
I'll give it a try.

**Comment by ilpersi** [comment] 2020-02-01 21:22
@MWEckert do you have any feedback on how it is going?

**Comment by MWEckert** [comment] 2020-02-01 23:12
Zero noticeable change.

**Comment by ilpersi** [comment] 2020-02-11 21:51
I reviewed the code once more and at the moment there is nothing I am able to change to fix this. I am sorry about this so I will mark this as wont fix.

I can only say that the latest version is pretty stable for me: I have it running from more than a week with no issues so far

**Comment by MWEckert** [comment] 2020-02-11 22:00
I don't know what, if anything, changed, but I've been a lot more stable.
Haven't had an issue since the newest version went live.

**Closed** 2020-03-15 13:11 UTC
Labels: wontfix

**Comment by ilpersi** [comment] 2020-03-20 15:57
@MWEckert I encourage you to update to the new [v44.1](https://github.com/ilpersi/BHBot/releases/tag/v44.1) just released. If fixes a very long-standing memory leak issue in BHBot core.

Based on my findings, the issue reported in this thread, is affected by resource availability so this can be one more step to increased stability.

**Comment by MWEckert** [comment] 2020-03-21 14:12
Awesome! Thank you so much.
