### ISSUE TITLE
GvG blocked until timeout

### ISSUE THREAD

**Issue by zenblob** [ilpersi/BHBot#163] opened 2020-05-21 01:15 UTC
**Describe the bug**
I noticed that very often the bot gets stuck in the beginning phase of the GvG.
after choosing the opponent, the log shows 'GVG initated!'
but in reality the key has not been pressed and the system times out, unless the 'accept' key is pressed.
it is difficult to reproduce the problem because it is random
no errors of any kind are shown

**Desktop (please complete the following information):**
 - OS:  Windows 10 
 - Browser Chromium]
 - Version 45

**Comment by zenblob** [comment] 2020-05-21 09:12
![image](https://user-images.githubusercontent.com/48311971/82543503-ec767b00-9b53-11ea-80d5-12d2c9f5299f.png)

**Comment by ilpersi** [comment] 2020-05-21 10:39
To investigate further I need the info contained in the screenshot/errors folder of BHBot.
At the time the error has been triggered, the bot has created two files a png and txt one: can you please attach them here?

Make sure to hide any personal information before you attach them.

**Comment by zenblob** [comment] 2020-05-21 10:48
![crash_20200521_1](https://user-images.githubusercontent.com/48311971/82551841-40d42780-9b61-11ea-89fc-8ea8cf592dd7.png)
[crash_20200521_1.txt](https://github.com/ilpersi/BHBot/files/4662000/crash_20200521_1.txt)
[crash_20200521_1.txt](https://github.com/ilpersi/BHBot/files/4662001/crash_20200521_1.txt)
![crash_20200521_1](https://user-images.githubusercontent.com/48311971/82551845-43cf1800-9b61-11ea-962c-d9a029a726da.png)

**Comment by ilpersi** [comment] 2020-05-21 10:59
Ok. GVG end is approaching so we try with an emergency fix. :)

Can you please stop the bot, replace your BHBot.jar with the one available [here](https://drive.google.com/u/0/uc?id=1Vtv2DZ44lxslnzEPoT_-dit_8MlW9jUV&export=download) and restart the bot?

I am not able to reproduce the issue so I basically added some more failsafe. This should work.
Let me know

**Comment by zenblob** [comment] 2020-05-21 12:43
now it seems ok, thank you

**Comment by Hunteil** [comment] 2020-05-21 15:10
I've seen this happen very rarely... Again with this being a walk away bot...it may reset it and I will come back to it in 4hrs and will never see it happen bc it got buried... But I have seen it and thought to myself... what are you doing? click go already! lol

Either-way at least it's not a huge waste like if you were in a middle of a dungeon crawl and you reset... The game will then remove the enemy encounter you were just in... I've had this kill off my boss encounter before.

**Comment by ilpersi** [comment] 2020-05-21 15:50
@Hunteil If you enable notifications, when this happens you get notified. It is the way I fix bugs. 😄 

As you can imagine my machine is not equal to other people machines so something that works on my machine may not work on other people machines. That being said it is impossible to be 100% crash-free.

The idea of the BOT is that you can do other stuff while it grinds for you. If you accept this idea you can also accept the fact that **rarely** there will be a crash and you may lose some resources. The cool thing is that even when something goes wrong, the bot keeps going.

I've had the bot run AFK for weeks with a really limited number of crashes (my record is 14 days in a row). When I restart the bot it is usually due to the fact that I have a new build with new feature/bug fixes.

**Comment by ilpersi** [comment] 2020-05-23 13:09
@zenblob As GVG is over I am closing this. If you have more issues, please open a new one.

**Closed by ilpersi** 2020-05-23 13:09 UTC
Labels: bug
