### ISSUE TITLE
v46 doesn’t do anything

### ISSUE THREAD

**Issue by MugenEnzan** [ilpersi/BHBot#176] opened 2020-07-26 07:24 UTC
**Describe the bug**
The bot doesn't start doing anything after loading

**To Reproduce**
1. Run the bot (vanilla or custom settings)
2. Wait for it to load and start Chrome
3. Bot finds game element
4. Nothing happens after

**Expected behavior**
The bot should run the game modes specified in the settings

**Screenshots**
NA

**Settings**
Vanilla settings

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Bundled Chromium
 - Version v46

**Additional context**
None of the game modes work, no bait collecting or bounties, it just says Starting to run bot... and that's it.

Edit: good news is it still detects idle loops and restarts Chromium and the bot.

**Comment by ilpersi** [comment] 2020-07-26 21:40
Please attach your `settings.ini` and the `log` of the bot when you start it.

**Comment by MugenEnzan** [comment] 2020-07-27 17:43
Here are the settings and logs from 46 and 46.1
Just ran both to test. No changes on my end.
[BHBot.zip](https://github.com/ilpersi/BHBot/files/4983536/BHBot.zip)

**Comment by ilpersi** [comment] 2020-07-27 20:25
This is usually caused by having a resolution above 1920x1200, DPI scaling above 100% or zooming the Chrome Window to a zoom different than 100%.

**Comment by MugenEnzan** [comment] 2020-07-28 07:26
Set resolution to 800x600, 100% DPI, and Chrome is set to 100%.

Still no changes, with both vanilla and custom settings.

Here is the latest log file.
[bhbot.log](https://github.com/ilpersi/BHBot/files/4986610/bhbot.log)

**Comment by ilpersi** [comment] 2020-07-29 06:57
You can go with 1920x1200 and it will be fine.
The issule looks different now: make sure to close all the Chromium opened windows before you start. If you are in doubt on how to close them all, just reboot you machine and run BHBot after the reboot.

**Comment by MugenEnzan** [comment] 2020-07-29 09:55
Sorry to report there are no changes :( 
Even tried with a fresh install of BHBot.

Any suggestions?

**Comment by ilpersi** [comment] 2020-07-29 13:38
Is this also happening with V45.2?

**Comment by MugenEnzan** [comment] 2020-07-29 18:11
[bhbot.log](https://github.com/ilpersi/BHBot/files/4996615/bhbot.log)

Unfortunately, yes. I checked my resolution, DPI scaling, and Chromium zoom levels. All are OK.

Rebooted several times, downloaded fresh copies of 46, 46.1, and 45.2. The log attached is from 45.2.

**Comment by ilpersi** [comment] 2020-07-29 20:22
Please do not run the bot in the download folder, but give it a dedicated folder in your HD.

Also: in the settings.ini can you please change from
`logLevel info`
to
`logLevel debug`
and attach again the logs?

Thank you

**Comment by MugenEnzan** [comment] 2020-07-29 21:07
Done. Created a new folder for 45.3, rebooted.

Here are the logs from 45.2 and 46.1
Don't mind the last error in 45.3 its when I manually closed Chromium.

I waited a bit to see if the bot did anything, then issued a manual `do trials` in 46.1 and `do pvp` in 45.2.
[bhbot45-2.log](https://github.com/ilpersi/BHBot/files/4997479/bhbot45-2.log)
[bhbot.log](https://github.com/ilpersi/BHBot/files/4997480/bhbot.log)

**Comment by ilpersi** [comment] 2020-08-02 10:50
My environment is different from yours and I am not able to reproduce this one.
I will try to re-create an environment similar to what you have: it will take me some time tough, please be patient. :)

**Comment by ilpersi** [comment] 2020-08-25 21:41
Sorry for the late answer.

I used an environment similar to yours and I was not able to reproduce the issue. It is something on your end even if I am not able to tell what the issue is. Usually this is related to screen configuration, so I created a new version to print out screen details.

You can find this version [here](https://drive.google.com/u/0/uc?id=1Vtv2DZ44lxslnzEPoT_-dit_8MlW9jUV&export=download): can you replace your BHBot.jar with this one and paste here the output of the `print screen-rect` command?

Thank you.

**Comment by ilpersi** [comment] 2020-09-02 08:30
@MugenEnzan is there any update?

**Comment by MugenEnzan** [comment] 2020-09-02 08:33
@ilpersi Sorry!!!
I was busy lately and didn't have much time for BH!

I will try out the new JAR over the weekend an update you with everything. I did have more issues lately with autoconsume and pushover integration, but I will provide everything over the weekend.

Also, I repurposed an old laptop solely for BHBot running Win10, so no more VMs. However, the issues persist.

I'll compile everything for you in a few days <3

**Comment by ilpersi** [comment] 2020-09-09 19:54
@MugenEnzan the newly release v46.2 contains the `print screen-rect` command mentioned before and many other fixes, please use that version to perform additional tests.

**Comment by ilpersi** [comment] 2020-09-23 11:29
@MugenEnzan long time, no update: do you still need help?

**Comment by MugenEnzan** [comment] 2020-09-23 11:32
@ilpersi so sorry, dude. Life has been hectic lately. 

I'll try and run the additional tests this weekend. 

Yes I still need help. The bot crashes a few times between runs, doesn't send push notifications, doesn't consume boosts... in any case, I'll have a full log for you as soon as I can. 

In the meantime, do tell me what kinda tests/runs/logs you might need so I know where to start troubleshooting. 

Thanks for your hard work and kind follow up 😁👍🏻

**Comment by ilpersi** [comment] 2020-09-28 20:58
@MugenEnzan I explained this a few times already, and I'll try to clarify it here also: bot crashing every now and then it is ok. 😊 I know it will sound weird and here is the idea: for many different reasons, it is almost impossible to foresee everything that is going to happen so sometimes the bot will crash.

The design however is made so that when this kind of unforeseen situation happens, the bot will reboot itself and it will keep going after the restart so you should only be worried if the bor crashes and it is not able to restart itself. The overall idea is to favor resilience and stability because even if you experiment some crashes; the outcome you get in the long run is much better of what you can get if you'd manually do that.

I personally have notifications turned on for crashes and if it is important I try to commit a fix as soon as possible.

Regarding the issues you mention:
- notifications: this is more probably a configuration issue. Please make sure to review wiki pages on [Discord](https://github.com/ilpersi/BHBot/wiki/Discord-integration-Documentation) and [Pushover](https://github.com/ilpersi/BHBot/wiki/Pushover-integration-Documentation)
- boots not being consumed is fixed in v45.2 (see #167 ), be sure to use it or event better update to the newest version

This issue was about you not being able to run the bot and it looks like this is no longer the case so I will close it. If you have different issues please raise an issue and choose the bug template (from [here](https://github.com/ilpersi/BHBot/issues/new/choose)) it will point out all the needed info for me to troubleshooting.

**Closed by ilpersi** 2020-09-28 20:58 UTC
Labels: bug
