### ISSUE TITLE
Make the bot use revive potions only on predefined slot(s)

### ISSUE THREAD

**Issue by RenuzitV** [ilpersi/BHBot#89] opened 2019-06-16 06:44 UTC
The current revive system always revives all characters that died, and in certain cases it could waste a lot of potions that wouldn't help the run at all, for instance running hard/heroic raids with the main character has very low ts/health compared to the team. It would help a lot if we can have a setting to only revive specific slots when checking for members to revive, and ignore the others. 

A solution to this could be to add `revivePositions x x x x x` where `x` is `0` or `1` depends on whether or not the user wants the character in that position to be revived upon death.

Edit : since the current revive system also supports t/g and expeditions, we would need to separate `revivePositions` into `revivePositionsRaids` and `revivePositions`, or make the first and second slot be front and rear, then the rest will be other positions from left to right.

**Comment by Fortigate** [comment] 2019-06-16 10:22
We have a mix of tankPriority and potionLimit to deal with this, I run priority on the tank for raid 7 and potionLimit of 3. This usually revives bait, tank and one dps worst case scenario, if it gets to that point the run is usually a defeat and it skips further revives.

**Comment by RenuzitV** [comment] 2019-06-16 15:17
Problem is that tankPriority always uses 100% revive, which can be costly and not needed (ex : getting 1 shot from gorbon’s once per adventure attack), and that may have to be changed. I also thought of an idea to just use `revivePotions x x x x x` where `x` is the type of potion you want to use for that position, along with `potionLimit`. This group up tankPriority and tankPosition and might be easier to use than the current revive system we have now.

**Comment by Fortigate** [comment] 2019-06-17 09:54
Yeah I can see that a system for activity and then position+potion type (E.G `r 1 3 3 3 2; t 3 3 1; g 3 3 1; e 3 3 3`) would be more flexible than the current system. The issue is that this would involve a pretty big rewrite of the current system. 

I have some small test changes to try with the current system I'll see how much work it would be to change it while I'm doing that.

**Comment by Fortigate** [comment] 2019-07-18 09:37
Closing this for now, changes to the autoRevive system are on my to-do list, but as the current system is functional it's low on my priority list.

**Closed by Fortigate** 2019-07-18 09:37 UTC
Labels: enhancement
