### ISSUE TITLE
Is Linux a supported platform?

### ISSUE THREAD

**Issue by bit-for-byte** [ilpersi/BHBot#134] opened 2019-11-03 21:03 UTC
I'm going thru the guide on the wiki page, but it seems geared for Windows. Is Linux a supported platform to run this on? Right now, it doesn't seem to be supported because I followed the guide and ran `init.bat` (which I renamed to `init.sh` and put `#!/usr/bin/env sh` at the top of the file). When I ran it, I got this error:

```
15:53:31,382 INFO - BHBot v42.9 build on Sun Nov 03 15:31:30 EST 2019 started.
15:53:31,389 INFO - GIT commit id: 10101a0cf02a36cdd8c3afa69f5207d0d3a3ff80  time: 2019-10-19T09:27:21+0200
15:53:32,605 INFO - Settings loaded from file
15:53:33,651 FATAL - Impossible to find Chromium executable in path C:\Users\username\AppData\Local\Chromium\Application\chrome.exe. Bot will be stopped!
```

**Comment by ilpersi** [comment] 2019-11-03 21:40
I actually never tested on linux (mainly for time constraints), so it is not officially supported.

That being said the code is completely portable so you may try to override the chromium executable path. To do so you have to change your `init.sh` from

`java -jar BHBot.jar init`

to 

`java -jar BHBot.jar init chromium <path_to_chromium executable>`

Please note: you have to specify the executable file itself, not just the folder containing it.

Let us know how it is going and if you need more assistance, there are a couple of other undocumented options that can help you. :)

**Comment by Fuzznimp** [comment] 2019-11-28 19:54
Hi there !

I'm running Ubuntu `18.04`.

I tried to run `java -jar BHBot.jar init chromium /snap/bin/chromium.chromedriver` but I still get the same error.

I'd love some help their :).

Cheers !

**Comment by ilpersi** [comment] 2019-11-28 22:44
You need to update to v43 as in v42.* there was an issue with argument parsing.

By the way I did some testing and currently linux is not working. This is now a duplicate of #137, so I am closing this.

**Closed by ilpersi** 2019-11-28 22:44 UTC
Labels: enhancement
