### ISSUE TITLE
pop-up cue not detected in gauntlets

### ISSUE THREAD

**Issue by Shadiezz** [ilpersi/BHBot#150] opened 2020-02-18 11:23 UTC
At the end of a gauntlet, I just get the error "Error: unable to close popup (X) securely; popup cue not deteted!

![image](https://user-images.githubusercontent.com/5568731/74731944-6d6a6180-5249-11ea-86f9-f72e82455c76.png)

**Comment by Shadiezz** [comment] 2020-02-19 09:24
its the same with expeditions

**Comment by Hunteil** [comment] 2020-02-19 13:29
Same here... expeditions are broken and will hang forever and newest zone seems to be ignored... won't leave zone screen I think. I keep coming back to the game and finding it with full energy. So I changed the zone. Ran 1 dungeon and it fixed. So I believe the last zone isn't recognized.

**Comment by Fortigate** [comment] 2020-02-19 14:18
Can you type `print version` in the console and post the results?

**Comment by Shadiezz** [comment] 2020-02-19 14:19
@Fortigate at work now, but its the latest version, downloaded yesterday from here: https://github.com/ilpersi/BHBot/releases/tag/v44

**Comment by Fortigate** [comment] 2020-02-19 14:22
Ah ok, it was an issue we had on older versions, I went over the dungeon complete detection code and hadn't seen it since.

I'll check over the code when I'm home and try and make a debug version to see where the issue is occurring.

**Comment by Shadiezz** [comment] 2020-02-19 14:23
It seems to happen on multiple screens where the "X" button isnt there but only the "Close"

**Comment by Hunteil** [comment] 2020-02-19 17:34
I'll do the print when I'm home as well. (at work now sry)

**Comment by ilpersi** [comment] 2020-02-24 09:10
@Hunteil do you have any update?

**Comment by ilpersi** [comment] 2020-03-01 21:39
7 days and no updates, closing this. Feel free to open a new one.

**Closed by ilpersi** 2020-03-01 21:39 UTC
Labels: bug
